// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MultiPageAppBeltman.Data;

namespace MultiPageAppBeltman.Migrations
{
    [DbContext(typeof(ContactContext))]
    partial class ContactContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MultiPageAppBeltman.Models.Contact", b =>
                {
                    b.Property<int>("ContactID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContactID");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            ContactID = 1,
                            Address = "642 Evergreen Terrace, Springfield, KY 12345",
                            Name = "Homer Simpson",
                            Notes = "Met at Moes",
                            Phone = "555-555-5555"
                        },
                        new
                        {
                            ContactID = 2,
                            Address = "123 Fake St, Springfield, KY 12345",
                            Name = "Lenny Leonard",
                            Notes = "Stonecutter #12",
                            Phone = "555-555-5555"
                        },
                        new
                        {
                            ContactID = 3,
                            Address = "987 Fake St, Springfield, KY 12345",
                            Name = "Carl Carlson",
                            Notes = "Stonecutter #14",
                            Phone = "555-555-5555"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
